version: "3"

services:
  fa6:
    container_name: fa6
    restart: unless-stopped
    build:
      context: ./
    ports:
      - 0.0.0.0:${PORT}:${PORT}
    logging:
      driver: "json-file"
      options:
        max-size: 10m
        max-file: "2"
    command: "python start.py"
    networks:
      - v1-network

networks:
  v1-network:
    external: true
